// Mock data for development preview — shown when backend is unreachable
// Replace with real data by running backend/migrations/002_seed_test_data.sql

// picsum.photos — always loads, consistent per seed
const p = (seed: string) => `https://picsum.photos/seed/${seed}/600/800`;

export const MOCK_LISTINGS = [
  {
    id: 'mock-1',
    brand: 'Hermès',
    name: 'Birkin 30 Togo Leather',
    category: 'Bags',
    condition: 'Excellent',
    price: 45000,
    original_price: 52000,
    description: 'Iconic Birkin 30 in Toffee Togo leather with Palladium hardware. Stamp T (2015). Authenticated by WIMC.',
    photos: [p('hermes-birkin'), p('hermes-bag')],
    status: 'published',
    featured: true,
    bidding: true,
    bids: [{ u: 'User1', amt: 46000 }, { u: 'User2', amt: 47500 }],
    celebrity_id: 'celeb-1',
    wimc_profiles: { display_name: 'Sarelle Closet', avatar_url: null },
  },
  {
    id: 'mock-2',
    brand: 'Chanel',
    name: 'Classic Flap Medium Caviar',
    category: 'Bags',
    condition: 'Like New',
    price: 22500,
    original_price: null,
    description: 'Medium Classic Flap in black caviar leather with gold hardware. Series 28. Comes with full set.',
    photos: [p('chanel-flap'), p('chanel-bag')],
    status: 'published',
    featured: true,
    bidding: true,
    bids: [{ u: 'User3', amt: 23000 }],
    celebrity_id: 'celeb-1',
    wimc_profiles: { display_name: 'Sarelle Closet', avatar_url: null },
  },
  {
    id: 'mock-3',
    brand: 'Louis Vuitton',
    name: 'Speedy 25 Monogram',
    category: 'Bags',
    condition: 'Very Good',
    price: 3800,
    original_price: 4800,
    description: 'Classic Speedy 25 in LV Monogram canvas. Light honey patina. Date code CA3161.',
    photos: [p('lv-speedy'), p('lv-bag')],
    status: 'published',
    featured: true,
    bidding: true,
    bids: [],
    celebrity_id: 'celeb-1',
    wimc_profiles: { display_name: 'Sarelle Closet', avatar_url: null },
  },
  {
    id: 'mock-4',
    brand: 'Rolex',
    name: 'Datejust 36 Silver Dial',
    category: 'Watches',
    condition: 'Excellent',
    price: 18500,
    original_price: 21000,
    description: 'Rolex Datejust 36mm Oystersteel with silver Roman numeral dial. Reference 126234. 2021 with box and papers.',
    photos: [p('rolex-watch'), p('rolex-datejust')],
    status: 'published',
    featured: true,
    bidding: true,
    bids: [{ u: 'User4', amt: 19000 }, { u: 'User5', amt: 19800 }],
    celebrity_id: 'celeb-2',
    wimc_profiles: { display_name: 'Sarelle Closet', avatar_url: null },
  },
  {
    id: 'mock-5',
    brand: 'Louboutin',
    name: 'So Kate 120mm Patent Leather',
    category: 'Shoes',
    condition: 'Very Good',
    price: 750,
    original_price: 1050,
    description: 'Iconic So Kate pump in black patent leather. 120mm heel. Size EU 38. Worn twice.',
    photos: [p('louboutin-heels'), p('louboutin-shoe')],
    status: 'published',
    featured: false,
    bidding: false,
    wimc_profiles: { display_name: 'Sarelle Closet', avatar_url: null },
  },
  {
    id: 'mock-6',
    brand: 'Gucci',
    name: 'GG Marmont Small Shoulder Bag',
    category: 'Bags',
    condition: 'Like New',
    price: 2200,
    original_price: null,
    description: 'Small GG Marmont in black matelassé chevron leather. Gold-tone Double G hardware.',
    photos: [p('gucci-marmont'), p('gucci-bag')],
    status: 'published',
    featured: false,
    bidding: false,
    wimc_profiles: { display_name: 'Sarelle Closet', avatar_url: null },
  },
  {
    id: 'mock-7',
    brand: 'Cartier',
    name: 'Love Bracelet 18K Yellow Gold',
    category: 'Jewellery',
    condition: 'Excellent',
    price: 8500,
    original_price: 9800,
    description: '18K yellow gold Love bracelet with 4 diamonds. Size 17. Original box and receipt.',
    photos: [p('cartier-bracelet'), p('cartier-gold')],
    status: 'published',
    featured: true,
    bidding: true,
    bids: [{ u: 'User6', amt: 8800 }],
    celebrity_id: 'celeb-2',
    wimc_profiles: { display_name: 'Sarelle Closet', avatar_url: null },
  },
  {
    id: 'mock-8',
    brand: 'Dior',
    name: 'Lady Dior Medium Cannage',
    category: 'Bags',
    condition: 'Very Good',
    price: 5800,
    original_price: 7200,
    description: 'Lady Dior medium in blush pink lambskin with light gold hardware. Full set with charms.',
    photos: [p('dior-lady'), p('dior-bag')],
    status: 'published',
    featured: false,
    bidding: false,
    wimc_profiles: { display_name: 'Sarelle Closet', avatar_url: null },
  },
  {
    id: 'mock-9',
    brand: 'Valentino',
    name: 'Garavani Rockstud Pumps 100mm',
    category: 'Shoes',
    condition: 'Good',
    price: 620,
    original_price: 1100,
    description: 'Iconic Rockstud pump in nude leather with pyramid studs. 100mm heel. Size EU 37.5.',
    photos: [p('valentino-rockstud'), p('valentino-pump')],
    status: 'published',
    featured: false,
    bidding: false,
    wimc_profiles: { display_name: 'Sarelle Closet', avatar_url: null },
  },
  {
    id: 'mock-10',
    brand: 'Prada',
    name: 'Re-Edition 2005 Nylon Shoulder Bag',
    category: 'Bags',
    condition: 'Like New',
    price: 1450,
    original_price: null,
    description: 'Iconic Re-Edition 2005 in black Re-Nylon. Triangular logo plaque. Worn once — pristine.',
    photos: [p('prada-nylon'), p('prada-bag')],
    status: 'published',
    featured: false,
    bidding: false,
    wimc_profiles: { display_name: 'Sarelle Closet', avatar_url: null },
  },
];

export const MOCK_CELEBRITIES = [
  {
    id: 'celeb-1',
    name: 'Yasmine Sabri',
    bio: 'Actress',
    followers: '2.1M',
    verified: true,
    totalItems: 3,
    listings: [MOCK_LISTINGS[0], MOCK_LISTINGS[1], MOCK_LISTINGS[2]],
  },
  {
    id: 'celeb-2',
    name: 'Hend Sabry',
    bio: 'Actress',
    followers: '3.4M',
    verified: true,
    totalItems: 2,
    listings: [MOCK_LISTINGS[3], MOCK_LISTINGS[6]],
  },
  {
    id: 'celeb-3',
    name: 'Amr Diab',
    bio: 'Singer',
    followers: '8.2M',
    verified: true,
    totalItems: 1,
    listings: [MOCK_LISTINGS[7]],
  },
  {
    id: 'celeb-4',
    name: 'Mohamed Ramadan',
    bio: 'Actor',
    followers: '5.8M',
    verified: true,
    totalItems: 0,
    listings: [],
  },
];
